project:
  type: website
  output-dir: docs

website:
  title: "Jackson_Marsh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - about2.qmd
      - Untitled.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

